### ISSUE TITLE
push -R is broken 

### ISSUE THREAD

**Issue by eee-c** [eee-c/couch_docs#10]
$ ./bin/couch-docs push -R localhost:5984/test3 /tmp/test2
/home/cstrom/.rvm/gems/ruby-1.8.7-p302@couch_docs/gems/rest-client-1.1.0/lib/restclient/request.rb:209:in `process_result': HTTP status code 400 (RestClient::RequestFailed)
        from /home/cstrom/.rvm/gems/ruby-1.8.7-p302@couch_docs/gems/rest-client-1.1.0/lib/restclient/request.rb:139:in`transmit'
        from /home/cstrom/.rvm/rubies/ruby-1.8.7-p302/lib/ruby/1.8/net/http.rb:543:in `start'
        from /home/cstrom/.rvm/gems/ruby-1.8.7-p302@couch_docs/gems/rest-client-1.1.0/lib/restclient/request.rb:137:in`transmit'
        from /home/cstrom/.rvm/gems/ruby-1.8.7-p302@couch_docs/gems/rest-client-1.1.0/lib/restclient/request.rb:60:in `execute_inner'
        from /home/cstrom/.rvm/gems/ruby-1.8.7-p302@couch_docs/gems/rest-client-1.1.0/lib/restclient/request.rb:50:in`execute'
        from /home/cstrom/.rvm/gems/ruby-1.8.7-p302@couch_docs/gems/rest-client-1.1.0/lib/restclient/request.rb:28:in `execute'
        from /home/cstrom/.rvm/gems/ruby-1.8.7-p302@couch_docs/gems/rest-client-1.1.0/lib/restclient.rb:79:in`delete'
        from /home/cstrom/repos/couch_docs/lib/couch_docs/store.rb:58:in `delete'
        from /home/cstrom/repos/couch_docs/lib/couch_docs/store.rb:39:in`delete_and_put'
        from /home/cstrom/repos/couch_docs/lib/couch_docs/store.rb:35:in `put!'
        from /home/cstrom/repos/couch_docs/lib/couch_docs.rb:80:in`destructive_database_create'
        from /home/cstrom/repos/couch_docs/lib/couch_docs/command_line.rb:30:in `run'
        from /home/cstrom/repos/couch_docs/lib/couch_docs/command_line.rb:13:in`run'
        from ./bin/couch-docs:10

**Comment by eee-c** [comment]
Don&#39;t pass empty _rev when deleting. closed by a49b04fdd44b95bfaae6b551a1fa6b8744549efa
